//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaKashService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaKashService.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AGENTLOGIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AGENTLOGINAsync(string AgentID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AGENTLOGOUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AGENTLOGOUTAsync(string AgentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GENERATEOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GENERATEOTPAsync(string AgentID, string Mobile, string SessionID, string ServiceName, string Email, string Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSTOMERREGISTRATION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CUSTOMERREGISTRATIONAsync(string AgentID, string Mobile, string SessionID, string Email, string FirstName, string MiddleName, string LastName, string DOB, string Gender, string OTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSTOMERREGISTRATION_FULLKYC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CUSTOMERREGISTRATION_FULLKYCAsync(
                    string AgentID, 
                    string CustomerID, 
                    string WalletType, 
                    string Mobile, 
                    string SessionID, 
                    string Email, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string DOB, 
                    string Gender, 
                    string Address1, 
                    string Address2, 
                    string Post, 
                    string PIN, 
                    string District, 
                    string State, 
                    string Nationality, 
                    string KYCMethod, 
                    string KYCType, 
                    string KYCNumber, 
                    string KYCCode, 
                    string OTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSTOMERUPDATE_FULLKYC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CUSTOMERUPDATE_FULLKYCAsync(
                    string AgentID, 
                    string CustomerID, 
                    string WalletType, 
                    string Mobile, 
                    string SessionID, 
                    string Email, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string DOB, 
                    string Gender, 
                    string Address1, 
                    string Address2, 
                    string Post, 
                    string PIN, 
                    string District, 
                    string State, 
                    string Nationality, 
                    string KYCMethod, 
                    string KYCType, 
                    string KYCNumber, 
                    string KYCCode, 
                    string OTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETCUSTOMERPROFILE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GETCUSTOMERPROFILEAsync(string AgentID, string Mobile, string SessionID, string Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WALLETTOPUP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> WALLETTOPUPAsync(string AgentID, string Password, string Mobile, string SessionID, string Amount, string RequestID, string PaymentMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADMINLOGIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ADMINLOGINAsync(string AdminID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TRANSREVERSAL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TRANSREVERSALAsync(string AdminID, string Mobile, string SessionID, string TransactionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxnStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TxnStatusAsync(string AgentID, string Password, string Mobile, string SessionID, string Amount, string RequestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACCOUNTTRANSFER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ACCOUNTTRANSFERAsync(string AgentID, string Mobile, string SessionID, string Amount, string BenAccounNumber, string BenAccoun_IFSC, string Ben_Name, string OTP, string Password, string RequestID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface Service1SoapChannel : MaKashService.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<MaKashService.Service1Soap>, MaKashService.Service1Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> AGENTLOGINAsync(string AgentID, string Password)
        {
            return base.Channel.AGENTLOGINAsync(AgentID, Password);
        }
        
        public System.Threading.Tasks.Task<string> AGENTLOGOUTAsync(string AgentID)
        {
            return base.Channel.AGENTLOGOUTAsync(AgentID);
        }
        
        public System.Threading.Tasks.Task<string> GENERATEOTPAsync(string AgentID, string Mobile, string SessionID, string ServiceName, string Email, string Amount)
        {
            return base.Channel.GENERATEOTPAsync(AgentID, Mobile, SessionID, ServiceName, Email, Amount);
        }
        
        public System.Threading.Tasks.Task<string> CUSTOMERREGISTRATIONAsync(string AgentID, string Mobile, string SessionID, string Email, string FirstName, string MiddleName, string LastName, string DOB, string Gender, string OTP)
        {
            return base.Channel.CUSTOMERREGISTRATIONAsync(AgentID, Mobile, SessionID, Email, FirstName, MiddleName, LastName, DOB, Gender, OTP);
        }
        
        public System.Threading.Tasks.Task<string> CUSTOMERREGISTRATION_FULLKYCAsync(
                    string AgentID, 
                    string CustomerID, 
                    string WalletType, 
                    string Mobile, 
                    string SessionID, 
                    string Email, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string DOB, 
                    string Gender, 
                    string Address1, 
                    string Address2, 
                    string Post, 
                    string PIN, 
                    string District, 
                    string State, 
                    string Nationality, 
                    string KYCMethod, 
                    string KYCType, 
                    string KYCNumber, 
                    string KYCCode, 
                    string OTP)
        {
            return base.Channel.CUSTOMERREGISTRATION_FULLKYCAsync(AgentID, CustomerID, WalletType, Mobile, SessionID, Email, FirstName, MiddleName, LastName, DOB, Gender, Address1, Address2, Post, PIN, District, State, Nationality, KYCMethod, KYCType, KYCNumber, KYCCode, OTP);
        }
        
        public System.Threading.Tasks.Task<string> CUSTOMERUPDATE_FULLKYCAsync(
                    string AgentID, 
                    string CustomerID, 
                    string WalletType, 
                    string Mobile, 
                    string SessionID, 
                    string Email, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string DOB, 
                    string Gender, 
                    string Address1, 
                    string Address2, 
                    string Post, 
                    string PIN, 
                    string District, 
                    string State, 
                    string Nationality, 
                    string KYCMethod, 
                    string KYCType, 
                    string KYCNumber, 
                    string KYCCode, 
                    string OTP)
        {
            return base.Channel.CUSTOMERUPDATE_FULLKYCAsync(AgentID, CustomerID, WalletType, Mobile, SessionID, Email, FirstName, MiddleName, LastName, DOB, Gender, Address1, Address2, Post, PIN, District, State, Nationality, KYCMethod, KYCType, KYCNumber, KYCCode, OTP);
        }
        
        public System.Threading.Tasks.Task<string> GETCUSTOMERPROFILEAsync(string AgentID, string Mobile, string SessionID, string Amount)
        {
            return base.Channel.GETCUSTOMERPROFILEAsync(AgentID, Mobile, SessionID, Amount);
        }
        
        public System.Threading.Tasks.Task<string> WALLETTOPUPAsync(string AgentID, string Password, string Mobile, string SessionID, string Amount, string RequestID, string PaymentMode)
        {
            return base.Channel.WALLETTOPUPAsync(AgentID, Password, Mobile, SessionID, Amount, RequestID, PaymentMode);
        }
        
        public System.Threading.Tasks.Task<string> ADMINLOGINAsync(string AdminID, string Password)
        {
            return base.Channel.ADMINLOGINAsync(AdminID, Password);
        }
        
        public System.Threading.Tasks.Task<string> TRANSREVERSALAsync(string AdminID, string Mobile, string SessionID, string TransactionNumber)
        {
            return base.Channel.TRANSREVERSALAsync(AdminID, Mobile, SessionID, TransactionNumber);
        }
        
        public System.Threading.Tasks.Task<string> TxnStatusAsync(string AgentID, string Password, string Mobile, string SessionID, string Amount, string RequestID)
        {
            return base.Channel.TxnStatusAsync(AgentID, Password, Mobile, SessionID, Amount, RequestID);
        }
        
        public System.Threading.Tasks.Task<string> ACCOUNTTRANSFERAsync(string AgentID, string Mobile, string SessionID, string Amount, string BenAccounNumber, string BenAccoun_IFSC, string Ben_Name, string OTP, string Password, string RequestID)
        {
            return base.Channel.ACCOUNTTRANSFERAsync(AgentID, Mobile, SessionID, Amount, BenAccounNumber, BenAccoun_IFSC, Ben_Name, OTP, Password, RequestID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://onpay.online.manappuram.com/test_ma/Makash_service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://onpay.online.manappuram.com/test_ma/Makash_service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
